#!/bin/bash

# OPENVPN SERVER SETTINGS
cd /etc/openvpn;mkdir log
wget "https://raw.githubusercontent.com/X-DCB/Unix/master/openvpn/openvpn_X-DCB.tar" -qO- | tar x
wget -qO 1194.conf https://raw.githubusercontent.com/X-DCB/Unix/master/openvpn/1194.conf
sysctl -w net.ipv4.ip_forward=1
sed -i 's/#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/g' /etc/sysctl.conf
# create IP Table Service
echo 1 > /proc/sys/net/ipv4/ip_forward
echo "[Unit]
Description=OpenVPN IP Table
[Service]
ExecStart=/sbin/iptab
StandardOutput=null
[Install]
WantedBy=multi-user.target" > /etc/systemd/system/iptab.service
echo '#!/bin/bash
iptables -A FORWARD -j REJECT --reject-with icmp-port-unreachable
iptables -I INPUT -i tun+ -j ACCEPT
iptables -I FORWARD -i tun+ -j ACCEPT
iptables -I INPUT -i tap+ -j ACCEPT
iptables -I FORWARD -i tap+ -j ACCEPT
iptables -I FORWARD -s 10.8.0.0/24 -j ACCEPT
iptables -t nat -I POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE
iptables -t nat -I POSTROUTING 2 -s 10.8.0.0/24 -j SNAT --to-source $(wget -qO- ipv4.icanhazip.com)
iptables -I FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT' > /sbin/iptab
# executability
chmod +x {/sbin/iptab,/etc/systemd/system/iptab.service}
# install squid
cd
# restart services
systemctl restart {squid3,openvpn,iptab,nginx,mysql,php5.6-fpm}
# enable on startup
systemctl enable {squid3,openvpn,iptab,nginx,mysql,php5.6-fpm}
clear
wget -qO- "https://raw.githubusercontent.com/X-DCB/Unix/master/banner" | bash
echo 'Your Squid Proxy is'$rpstat' shareable.'
echo "Installation finished."
